# generated by datamodel-codegen:
#   filename:  organizations.json
#   timestamp: 2021-03-17T08:08:59+00:00

from __future__ import annotations

from pydantic import BaseModel
from typing import List


class Organization(BaseModel):
    _id: int
    url: str
    external_id: str
    name: str
    domain_names: List[str]
    created_at: str
    details: str
    shared_tickets: bool
    tags: List[str]


class Organizations(BaseModel):
    __root__: List[Organization]
